name: Release Please

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      skip-tests:
        description: 'Skip tests and linting (not recommended)'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  lint-and-test:
    # Run only for manual dispatch on master
    if: github.ref == 'refs/heads/master'
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ github.event.inputs.skip-tests == 'false' && github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v5

      - name: Setup Helm
        if: ${{ github.event.inputs.skip-tests == 'false' && github.event_name == 'workflow_dispatch' }}
        uses: azure/setup-helm@v4
        
      # Run Lint and Pester tests only if not skipped
      - name: Lint (PSScriptAnalyzer)
        if: ${{ github.event.inputs.skip-tests == 'false' && github.event_name == 'workflow_dispatch' }}
        uses: podcamp/Action-PSScriptAnalyzer@v1
        with:
          module-path: src
          test-path: tests
          upload-artifact: 'true'
          throw-on-warnings: 'false'
          throw-on-errors: 'true'
          throw-on-test-failures: 'true'
  
  release-please:
    # Run only on manual dispatch or on push with a release-please bump commit message
    if: |
      github.ref == 'refs/heads/master' && 
      (
        (github.event_name == 'workflow_dispatch' && needs.lint-and-test.result == 'success')
        ||
          (
              github.event_name == 'push' && 
              (
                contains(github.event.head_commit.message, 'chore(master): release') ||
                contains(github.event.head_commit.message, 'chore: release') ||
                contains(toJSON(github.event.commits), 'chore(master): release') ||
                contains(toJSON(github.event.commits), 'chore: release')
              )
          )
      )
    needs: lint-and-test
    name: Create or update release PR
    runs-on: ubuntu-latest
    concurrency:
      group: release-please-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Release Please
        uses: podcamp/Action-ReleasePlease@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
